name: tekartik_utils
version: 0.2.0
description: Common dart utilities
dependencies:
  browser: any
  collection: any
  logging: any
  pub_semver: any
#  tekartik_core:
#    git: git://github.com/alextekartik/tekartik_core.dart
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart1
dev_dependencies:
  test: any
  dev_test: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart1
    version: '>=0.1.3'
dependency_overrides:
#  tekartik_common_utils:
#    path: ../../tekartik/common_utils.dart
  
