name: tekartik_utils
version: 0.0.7
description: Common dart utilities
dependencies:
  browser: any
  collection: any
  logging: any
  tekartik_core:
    git: git://github.com/alextekartik/tekartik_core.dart
dev_dependencies:
  test: any
dependency_overrides:
#  tekartik_core:
#    path: ../tekartik_core.dart
  
